# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_channel_template.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddChannelDialog(object):
    def setupUi(self, AddChannelDialog):
        AddChannelDialog.setObjectName("AddChannelDialog")
        AddChannelDialog.setWindowModality(QtCore.Qt.WindowModal)
        AddChannelDialog.resize(506, 124)
        self.buttons_box = QtWidgets.QDialogButtonBox(AddChannelDialog)
        self.buttons_box.setGeometry(QtCore.QRect(237, 58, 261, 32))
        self.buttons_box.setOrientation(QtCore.Qt.Horizontal)
        self.buttons_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttons_box.setCenterButtons(False)
        self.buttons_box.setObjectName("buttons_box")
        self.url_edit_line = QtWidgets.QLineEdit(AddChannelDialog)
        self.url_edit_line.setGeometry(QtCore.QRect(10, 60, 311, 27))
        self.url_edit_line.setText("")
        self.url_edit_line.setObjectName("url_edit_line")
        self.label = QtWidgets.QLabel(AddChannelDialog)
        self.label.setGeometry(QtCore.QRect(96, 10, 331, 41))
        self.label.setObjectName("label")
        self.open_box = QtWidgets.QDialogButtonBox(AddChannelDialog)
        self.open_box.setGeometry(QtCore.QRect(-20, 16, 111, 32))
        self.open_box.setOrientation(QtCore.Qt.Horizontal)
        self.open_box.setStandardButtons(QtWidgets.QDialogButtonBox.Open)
        self.open_box.setCenterButtons(False)
        self.open_box.setObjectName("open_box")
        self.error_label = QtWidgets.QLabel(AddChannelDialog)
        self.error_label.setGeometry(QtCore.QRect(13, 94, 341, 19))
        self.error_label.setText("")
        self.error_label.setObjectName("error_label")

        self.retranslateUi(AddChannelDialog)
        self.buttons_box.accepted.connect(AddChannelDialog.accept)
        self.buttons_box.rejected.connect(AddChannelDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AddChannelDialog)

    def retranslateUi(self, AddChannelDialog):
        _translate = QtCore.QCoreApplication.translate
        AddChannelDialog.setWindowTitle(_translate("AddChannelDialog", "Dialog"))
        self.url_edit_line.setPlaceholderText(_translate("AddChannelDialog", "e.g. https://website.com/nature/owl.mp3"))
        self.label.setText(_translate("AddChannelDialog", "mp3 from local files or download mp3 from url:"))
