# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'docked_channels_template.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_channel_dock_main(object):
    def setupUi(self, channel_dock_main):
        channel_dock_main.setObjectName("channel_dock_main")
        channel_dock_main.setWindowModality(QtCore.Qt.ApplicationModal)
        channel_dock_main.resize(111, 250)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(channel_dock_main.sizePolicy().hasHeightForWidth())
        channel_dock_main.setSizePolicy(sizePolicy)
        channel_dock_main.setMinimumSize(QtCore.QSize(0, 222))
        channel_dock_main.setMaximumSize(QtCore.QSize(700, 244))
        channel_dock_main.setLayoutDirection(QtCore.Qt.LeftToRight)
        channel_dock_main.setAutoFillBackground(False)
        channel_dock_main.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        channel_dock_main.setDockNestingEnabled(False)
        channel_dock_main.setDockOptions(QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(channel_dock_main)
        self.centralwidget.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        channel_dock_main.setCentralWidget(self.centralwidget)
        # self.template_dock = QtWidgets.QDockWidget(channel_dock_main)
        # sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.template_dock.sizePolicy().hasHeightForWidth())
        # self.template_dock.setSizePolicy(sizePolicy)
        # self.template_dock.setMinimumSize(QtCore.QSize(111, 222))
        # self.template_dock.setMaximumSize(QtCore.QSize(111, 222))
        # font = QtGui.QFont()
        # font.setFamily("Cantarell")
        # font.setPointSize(9)
        # self.template_dock.setFont(font)
        # self.template_dock.setFeatures(QtWidgets.QDockWidget.DockWidgetMovable)
        # self.template_dock.setAllowedAreas(QtCore.Qt.TopDockWidgetArea)
        # self.template_dock.setObjectName("template_dock")
        # self.dockWidgetContents = QtWidgets.QWidget()
        # sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.dockWidgetContents.sizePolicy().hasHeightForWidth())
        # self.dockWidgetContents.setSizePolicy(sizePolicy)
        # self.dockWidgetContents.setMinimumSize(QtCore.QSize(111, 222))
        # self.dockWidgetContents.setMaximumSize(QtCore.QSize(111, 222))
        # self.dockWidgetContents.setObjectName("dockWidgetContents")
        # self.template_dock.setWidget(self.dockWidgetContents)
        # channel_dock_main.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.template_dock)

        self.retranslateUi(channel_dock_main)
        QtCore.QMetaObject.connectSlotsByName(channel_dock_main)

    def retranslateUi(self, channel_dock_main):
        _translate = QtCore.QCoreApplication.translate
        channel_dock_main.setWindowTitle(_translate("channel_dock_main", "MainWindow"))
        #self.template_dock.setWindowTitle(_translate("channel_dock_main", "text area"))
