
# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__author__ = 'Eskil Oscar Ehrensvärd'
__homepage__ = 'https://github.com/Ehrensverd/Bard-bot'
__version__ = '0.1.dev33+gf8f5522'
